// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYvoUDexlQBpgOH6H1vfMQV605bqDYlhk',
    appId: '1:1096519450958:web:79e20ddfac9f52e7a25e1f',
    messagingSenderId: '1096519450958',
    projectId: 'unitvixpro',
    authDomain: 'unitvixpro.firebaseapp.com',
    databaseURL: 'https://unitvixpro-default-rtdb.firebaseio.com',
    storageBucket: 'unitvixpro.appspot.com',
    measurementId: 'G-ZK8T4KDLT1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf8Ee02IeUKkHWN_Yeb2MLLZsNNlf83Lc',
    appId: '1:1096519450958:android:37848c89d5402895a25e1f',
    messagingSenderId: '1096519450958',
    projectId: 'unitvixpro',
    databaseURL: 'https://unitvixpro-default-rtdb.firebaseio.com',
    storageBucket: 'unitvixpro.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0rSkzEErhg8S5XCv4UYlORhakOVXtvvM',
    appId: '1:1096519450958:ios:c0f2312936f3897fa25e1f',
    messagingSenderId: '1096519450958',
    projectId: 'unitvixpro',
    databaseURL: 'https://unitvixpro-default-rtdb.firebaseio.com',
    storageBucket: 'unitvixpro.appspot.com',
    iosBundleId: 'com.example.unitvizp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0rSkzEErhg8S5XCv4UYlORhakOVXtvvM',
    appId: '1:1096519450958:ios:c0f2312936f3897fa25e1f',
    messagingSenderId: '1096519450958',
    projectId: 'unitvixpro',
    databaseURL: 'https://unitvixpro-default-rtdb.firebaseio.com',
    storageBucket: 'unitvixpro.appspot.com',
    iosBundleId: 'com.example.unitvizp',
  );
}
